touchscreen: fts_lib: Fix strict-prototypes errors
clang-15 complains:
drivers/input/touchscreen/fts_touch/fts_lib/ftsIO.c:128:29: error: a
function declaration without a prototype is deprecated in all versions
of C [-Werror,-Wstrict-prototypes]
struct spi_device *getClient()
                            ^
                             void
drivers/input/touchscreen/st/fts_lib/ftsIO.c:85:22: error: a function
declaration without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
struct device *getDev()
                     ^
                      void
drivers/input/touchscreen/st/fts_lib/ftsIO.c:93:29: error: a function
declaration without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
struct i2c_client *getClient()
                            ^
                             void
drivers/input/touchscreen/st/fts_lib/ftsTime.c:95:16: error: a function
declaration without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
char *timestamp()
               ^
                void
4 errors generated.

Change-Id: Ia26d54281333d721deea15ef12bfe2cfe96349a8
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>